version: "3.3"

services:
  db:
    volumes: 
      - ./PSQLDATA:/var/lib/postgresql/data # YOUR/SERVER/DIR:CONTAINER/DIR
    build: ./SQL
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=uploader # Use lowercase.
      - POSTGRES_USER=admin # Use lowercase.
      - POSTGRES_PASSWORD= # CHANGE THIS TO SOMETHING LONG.
  web:
    volumes:
      - ./Uploader:/srv
    build: ./Uploader
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      - DBPASS=
  bot:
    volumes:
      - ./Bot:/srv
    build: ./Bot
    environment: 
      - TOKEN=
      - DBPASS=
    depends_on: 
      - db
      - web
