version: "3.9"

services:
  db:
    volumes: 
      - ./PSQLDATA:/var/lib/postgresql/data # YOUR/SERVER/DIR:CONTAINER/DIR
    build: ./SQL
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=uploader # Use lowercase.
      - POSTGRES_USER=admin # Use lowercase.
      - POSTGRES_PASSWORD=Pj+5K]hDT:FT>(8.
      - PGPASSWORD=Pj+5K]hDT:FT>(8.
  web:
    volumes:
      - ./Uploader:/srv
    environment:
        - DOMAIN=127.0.0.1 # The domain your server runs on.
    build: ./Uploader
    ports:
      - "80:8080"
    depends_on:
      - db
